# syntax=docker/dockerfile:1
FROM node:14-alpine
# ENV NODE_ENV production

WORKDIR /app

RUN apk update
RUN apk add curl
COPY package*.json ./
COPY prisma ./prisma/
COPY .env ./
# change to npm ci for production
RUN npm install
RUN npx prisma generate


COPY . .

# Not supported by heroku
# EXPOSE 3000

CMD ["npm", "start"]
